server:
  port: 8090



spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
#  thymeleaf:
#    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
#    mode: HTML5
#    #编码 可不用配置
#    encoding: UTF-8
#    #内容类别,可不用配置
#    content-type: text/html
#    #开发配置为false,避免修改模板还要重启服务器
#    cache: false
#    #配置模板路径，默认是templates，可以不用配置
#    prefix: classpath:/templates

  datasource:
    url: jdbc:mysql://develop.hulu.fj.cn:3306/ptcb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ptcb
    password: ptcb123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.xz.model
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  configuration:
    lazy-loading-enabled: true   #开启赖加载
    aggressive-lazy-loading: false
    lazy-load-trigger-methods: